Feature title component
Zenith-Inovacoes/m3auto-website pull request #1
Opened 2023-02-17 16:23 UTC by DanielMarcelino65

pull request

2023-02-17 20:43 UTC, RianErnesto requested changes
Preciso que faça as alterações solicitadas, por favor

2023-02-17 20:43 UTC, RianErnesto commented on src/components/Title/styled.ts
> +  line-height: 42px;
Algumas linhas aqui são desnecessárias e só estão enchendo o código, vou citá-las aqui:
`justify-content: center`
`text-align: center`
`width: fit-content`
`flex-direction: row`
`font-family: 'Chakra Petch` - será acrescentado posteriormente no tema
`font-weight: 700` - deve ser passado pelo Typography
`font-size: 32px` - deve ser passado pelo Typography
`line-height: 42px` - deve ser passado pelo Typography

2023-02-17 20:43 UTC, RianErnesto commented on src/components/Title/styled.ts
> +  max-width: 500px;
Eu não consegui entender muito bem esse `max-width: 500px`, me explica

2023-02-17 20:43 UTC, RianErnesto commented on src/components/Title/styled.ts
> +`;
Aqui é bom pensar numa forma que fique responsiva, já que se aumentar o `line-height` ou o `font-size` as bordas não vão acompanhar o tamanho, já que estão fixas em 46px.
Minha sugestão é pensar em algo envolvendo `position: absolute`.

2023-02-17 20:43 UTC, RianErnesto commented on src/components/Title/styled.ts
> +  `: null };
Pra evitar colocar o `null` no final, eu sugiro isso
```suggestion
  ${({variant}) => variant == 'secondary' && css`
    :after {
      height: 46px;
      margin-left: 18px;
      content: '';
      width: 5px;
      background-color: ${({ theme }) => theme.colors.primary};
      position: relative;
      display: inline-block;
    }
  
  `};
```

2023-02-18 15:56 UTC, DanielMarcelino65 commented on src/components/Title/styled.ts
> +  max-width: 500px;
foi pra tentar ajeitar um negocio, mas eu esqueci de tirar, irei retirar

2023-02-19 03:15 UTC, RianErnesto commented on src/components/Title/index.tsx
> +import light from "@/styles/theme/light";
Não pode importar os temas assim nos componentes, já que os temas só vão ser importados ou no `style.ts` ou no Theme Provider no `_app.tsx`

2023-02-19 03:17 UTC, RianErnesto requested changes

2023-02-19 03:17 UTC, RianErnesto commented on src/components/Title/index.tsx
> +        <Typography fontWeight={700} size={light.sizes.medium} lineHeight={light.sizes.large} color={light.colors.text}> {children} </Typography>
`<Typography fontWeight={700} size="small" color="text" lineHeight="1.75rem"> {children} </Typography>`

2023-02-19 03:39 UTC, RianErnesto approved these changes

2023-02-19 03:40 UTC, merged